"""initial schema

Revision ID: 32ec80315f74
Revises: 
Create Date: 2026-09-10 16:30:08.972628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ec80315f74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_tokens_email'), ['email'], unique=True)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('daily_checkin_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferred_checkin_hour', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_email'), ['email'], unique=True)

    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_message', sa.Text(), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('tasks_discussed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_user_id'), ['user_id'], unique=False)

    op.create_table('task_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('estimate_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('resources_json', sa.JSON(), nullable=True),
    sa.Column('task_hash', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_hash')
    )
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_records_user_id'))

    op.drop_table('task_records')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_user_id'))

    op.drop_table('call_logs')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_email'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('google_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_tokens_email'))

    op.drop_table('google_tokens')
    # ### end Alembic commands ###
