"""add last_synced_at to task_records

Revision ID: 3ff2270d42eb
Revises: 32ec80315f74
Create Date: 2026-09-10 16:31:12.342456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff2270d42eb'
down_revision: Union[str, None] = '32ec80315f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')

    # ### end Alembic commands ###
